language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install .
  - pip install black
  - pip install -r test-requirements.txt

script:
  - pytest
  - black --check --verbose mypkg
